### PR TITLE
Added Function for always send email to sender

### PR DESCRIPTION
**Pull request by druckgott**
Hallo, I have added the function to always send a email to the sender of the formular. It overwrites the joomla function.

### CODE REVIEW

**Comment by PeterMacej** [comment]
Hello,

I understand that you added a new option to always send a copy to the sender. What is it good for? Isn't the default Joomla implementation OK? There's a checkbox and the user (sender) can decide whether to get a copy or not. 
What if the user DOESN'T want to get any email copy? Now he simply leaves the checkbox empty:
form_scr

With your new setting, his option will be ignored and a copy will be sent to him anyway. I think it's not a good practice because it's not what the user expected.

**Comment by druckgott** [comment]
You have to check the button and if a person forgets it the mail was not send. I put an information on the mail what I want to have that every person gets it. And you can not set the checkbox on on Joomla default

I have also disabled the box on my side.

**Comment by PeterMacej** [comment]
The way the "copy to sender" is implemented in Joomla is correct. A user should receive a copy only if he selected this option.

Maybe what you mean is not a copy but an auto-responder? A message like:
"Thank you, we will contact you soon. Meanwhile, you can download our product at XYZ.
Your original message:
.....
"

If this is the case, it would be good to have. Please let me know.

**Comment by druckgott** [comment]
Yes and this this option it's possible

**Comment by PeterMacej** [comment]
The auto responder is implemented. The new version 1.1.0 was released.

**Comment by druckgott** [comment]
Perfekt 😁

**Pull request closed without merging**
